name: Docker build workflow
# NB: This will only run on PRs from the main repo and not forks
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories
on:
  pull_request:
    branches:
      - master
jobs:
  build-docker:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # NB: For PRs, this will create two Docker tags: sha-${GIT_SHA} and pr-${PR_NUMBER}
      # https://github.com/crazy-max/ghaction-docker-meta#overview
      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: gcr.io/xpn-heroic-1/heroic
          tag-sha: true
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
